apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: backend
  type: ClusterIP # 后端不需要对外暴露，只给 Nginx 访问
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Jenkins 会动态替换这里的 tag
        image: my-k8s-test-backend:latest 
        imagePullPolicy: IfNotPresent # 关键：强制使用本地镜像
        ports:
        - containerPort: 8082
        env:
        - name: DB_HOST
          value: "mysql"
        - name: REDIS_HOST
          value: "redis"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
