# Dockerfile.nginx
FROM nginx:alpine

# 删除 Nginx 默认的配置文件
RUN rm /etc/nginx/conf.d/default.conf

# 复制自定义的 Nginx 配置文件
COPY nginx/conf.d/ /etc/nginx/conf.d/

# 将前端构建产物复制到 Nginx 的默认网页目录
COPY nginx/html/dist/ /usr/share/nginx/html/
